version: "2"
vars:
  CONTAINER_USER: googler
  CONTAINER_GROUP: googler
  GOOGLE_CLOUD_SDK_VERSION: 300.0.0
  TERRAFORM_VERSION: 0.12.28
  # This is usually a Git hash in the CFT repo:
  CLOUD_FOUNDATION_TOOLKIT_VERSION: d6b9284

  TAG: huy123/cloud-shell:{{.GOOGLE_CLOUD_SDK_VERSION}}-{{.TERRAFORM_VERSION}}-{{.CLOUD_FOUNDATION_TOOLKIT_VERSION}}

tasks:
  build:
    cmds:
      - >
        sed
        's/GOOGLE_CLOUD_SDK_VERSION/{{.GOOGLE_CLOUD_SDK_VERSION}}/g'
        Dockerfile.template
        |
        docker build
        -t {{.TAG}}
        --build-arg CONTAINER_USER={{.CONTAINER_USER}}
        --build-arg CONTAINER_GROUP={{.CONTAINER_GROUP}}
        --build-arg TERRAFORM_VERSION={{.TERRAFORM_VERSION}}
        --build-arg CLOUD_FOUNDATION_TOOLKIT_VERSION={{.CLOUD_FOUNDATION_TOOLKIT_VERSION}}
        -
  push:
    cmds:
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - docker push {{.TAG}}
